version: '3.1'

services:
  mongodb-container:
    image: mongo
    container_name: mongodb-container
    ports:
      - 2717:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ben
      MONGO_INITDB_ROOT_PASSWORD: test

  mongo-express-container:
    image: mongo-express
    container_name: mongo-express
    links:
      - 'mongodb-container:mongo'
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ben
      ME_CONFIG_MONGODB_ADMINPASSWORD: test

  lighttpd-container:
    image: sebp/lighttpd
    container_name: lighttpd
    volumes:
      - /sc/web:/var/www/localhost/htdocs
    ports:
      - "8080:80"
    tty: true

  perl-container:
    image: perl
    container_name: perl
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - /sc/web:/usr/src/myapp
